---
twitter-to-kafka-service:
  twitter-keywords: 
    - Java
    - Microservices
    - Kafka
    - SpringBoot
    - ElasticSearch
  enable-mock-tweets: true
  mock-min-tweet-length: 5
  mock-max-tweet-length: 15
  mock-sleep-ms: 10000